spring:
  application:
    name: lionproject2-backend

  profiles:
    active: local

  threads:
    virtual:
      enabled: true

portone:
  store-id: ${PORTONE_STORE_ID}
  channel-key: ${PORTONE_CHANNEL_KEY}
  api-secret: ${PORTONE_API_SECRET}

payment:
  inicis:
    mid: ${INICIS_MID:INIpaytest}
    signkey: ${INICIS_SIGNKEY:SU5JTElURV9URVNUX1NJR05LRVk=}
    ini-api-key: ${INICIS_API_KEY:test}
    ini-api-iv: ${INICIS_API_IV:HYb3yQ4f65QL89==}
